name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências
        working-directory: app
        run: npm install

      - name: Rodar testes
        working-directory: app
        run: npm test

      - name: Build Docker Image
        run: docker build -t api-devops-seplag:latest ./docker

      - name: Executar Trivy Scan
        uses: aquasecurity/trivy-action@v0.2.0
        with:
          image-ref: api-devops-seplag:latest

      # Etapa opcional: Deploy via Ansible
      - name: Executar Playbook Ansible
        uses: appleboy/ansible-playbook-action@master
        with:
          playbook: ansible/playbook.yml
          inventory: ansible/inventory.ini

